Task_1_2_3
cjvth/OOP pull request #4
Opened 2022-10-23 16:59 UTC by cjvth

2022-10-24 08:21 UTC, alradish submitted a review, later dismissed
.

2022-11-04 08:15 UTC, alradish requested changes
Добавил замечаний, у вас есть время прислать правки до семинара

2022-11-04 08:15 UTC, alradish commented on Task_1_2_3/src/main/java/ru/nsu/cjvth/graph/AdjacencyListGraph.java
> +        }
А почему ввели такое ограничение?

2022-11-04 08:15 UTC, alradish commented on Task_1_2_3/src/main/java/ru/nsu/cjvth/graph/AdjacencyListGraph.java
> +    @SuppressWarnings("DuplicatedCode")
Если код и правда повторяется, стоит вынести его либо в default метод интерфейса, либо в утильный класс.

2022-11-04 08:15 UTC, alradish commented on Task_1_2_3/src/main/java/ru/nsu/cjvth/graph/IncidenceMatrixGraph.java
> +    public Map<N, Double> calculateDistancesFrom(N selectedVertex) {
Кажется в этих двух цикла есть код который можно было бы вынести в отдельный метод и вызывать его

2022-11-05 21:02 UTC, cjvth commented on Task_1_2_3/src/main/java/ru/nsu/cjvth/graph/AdjacencyListGraph.java
> +        }
Тогда сложно представить граф матрицой инцидентности. Есть вариант, если петля из А в А, сделать в колонке этого ребра только одно значение в строке А. Но тогда, чтобы узнать, действительно ли это петля, а не ребро в другую вершину, надо пройтись так по всему столбцу. Получаем на проверку соединённости A и A асимптотику O(E*V) вместо O(E). А делать отдельное хранение петель как-то не хочется, это уже не честная матрица инцидентности получится

2022-11-11 07:42 UTC, alradish approved these changes

2022-11-11 07:42 UTC, merged