Task-1-3-1
cjvth/OOP pull request #5
Opened 2022-11-08 15:37 UTC by cjvth

2022-11-11 08:09 UTC, alradish requested changes
Хорошее начало

2022-11-21 11:25 UTC, alradish requested changes

2022-11-21 11:25 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/cjvth/substring/Substring.java
> +        }
Две ветки этого ифа можно схлопнуть

2022-11-21 11:25 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/cjvth/substring/Substring.java
> +                if (pos >= lastEnd) {
Дублирование кода. У вас уже есть функцию считающая z функцию

2022-11-21 19:29 UTC, cjvth commented on Task_1_3_1/src/main/java/ru/nsu/cjvth/substring/Substring.java
> +                if (pos >= lastEnd) {
У меня есть функция, считающая честную z-функцию для массива, в неё я передаю шаблон подстроки. В верхней функции же я читаю буферами фрагменты из потока и сравниваю их с отдельно лежащей подстрокой. Этот код, будь он даже в одной функции, всё равно не получилось бы нормально соединить в один фрагмент.
Чтобы использовать отдельную функцию для каждого буфера, надо либо передавать в неё массив шаблон-разделитель-буфер и каждый раз считать функцию с самого начала, либо передавать ещё результат подсчёта для шаблона и где в этом массиве начинается буфер. И в конце этого массива при каждом вызове, кроме последнего, будет [длина шаблона] символов, которых надо передать в следующий раз снова, вдруг где-то там начало подходящей подстроки.
В общем, слишком неудобно и неэффективно так делать

2022-11-29 15:34 UTC, alradish requested changes

2022-11-29 15:34 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/cjvth/substring/Substring.java
> +                if (pos >= lastEnd) {
> надо либо передавать в неё массив шаблон-разделитель-буфер и каждый раз считать функцию с самого начала, либо передавать ещё результат подсчёта для шаблона и где в этом массиве начинается буфер.  

Всё верно. Первый вариант это буквально описание алгоритма. 
> И в конце этого массива при каждом вызове, кроме последнего, будет [длина шаблона] символов, которых надо передать в следующий раз снова, вдруг где-то там начало подходящей подстроки.  

Опять же абсолютно верно. Нужно аккуратно сдвигать текст который вы прочитали. Например, если у вас в массиве месте 4T + 1 (где T длина шаблона + 1 для разделителя), то можно сохранить нужный кусочек в конце, длинны Т (перенести в начало), и дочитать текст в нужную позицию (ещё 3Т)  

> В общем, слишком неудобно и неэффективно так делать

По идее получается ещё меньше кода

С просадкой производительности можно жить и оптимизировать потом. Но дублирование кода это категорически неприемлемо.

2022-11-30 16:59 UTC, cjvth commented
В итоге получилось больше кода, но только из-за того, что Integer зачем-то иммутабельный. Пришлось писать Last

2022-12-12 03:19 UTC, alradish approved these changes

2022-12-12 03:19 UTC, merged